name: net
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

dependencies:
  ext:
    git: 'https://github.com/lamtx/ext.git'
  http: ^1.3.0
  http_parser: ^4.1.2
  path: any

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
